sudo: false
env:
   - CXX=g++-4.8
addons:
  apt:
    sources:
    - mongodb-3.4-precise
    - ubuntu-toolchain-r-test
    packages:
    - mongodb-org-server
    - g++-4.8
language: node_js
node_js: 
  - "7"
services:
  - mongodb
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --compilers ts:ts-node/register 'test/**/*.test.ts' && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage